key-vis: draft for session3/chapter2.1
pingcap-incubator/tidb-in-action pull request #108
Opened 2020-03-07 15:46 UTC by ngaut

2020-03-07 16:29 UTC, breeswish commented on session3/chapter2/key-vis.md
> +# 识别集群热点和业务模式
我觉得可以在这边先介绍一下可以使用 Key Visualizer 识别集群热点和业务模式。

2020-03-07 16:30 UTC, breezewish reviewed
The rest LGTM

2020-03-08 01:25 UTC, ngaut commented on session3/chapter2/key-vis.md
> +# 识别集群热点和业务模式
加了一段简介引入

2020-03-08 01:43 UTC, c4pt0r requested changes

2020-03-08 01:43 UTC, c4pt0r commented on session3/chapter2/key-vis.md
> +业务开发人员面对这些问题有时候一脸问号，脑子里面快速过了一遍自己的业务，我大概有 一百多张表，每个都有增删改查/CRUD，还有各种统计汇总的业务，有很多请求还是用户触发的，这些问题真的是很难回答。很多业务的访问模式都可以在 TiDB dashboard 里面比较直观的观测到， DBA 和开发者能够一眼发现系统的读写比例，哪里有热点，甚至能够精确到哪个数据块，哪些索引，也能预测如果流量持续增长，数
```suggestion
业务开发人员面对这些问题有时候一脸问号，脑子里面快速过了一遍自己的业务，我大概有一百多张表，每个都有增删改查/CRUD，还有各种统计汇总的业务，有很多请求还是用户触发的，这些问题真的是很难回答。很多业务的访问模式都可以在 TiDB dashboard 里面比较直观的观测到， DBA 和开发者能够一眼发现系统的读写比例，哪里有热点，甚至能够精确到哪个数据块，哪些索引，也能预测如果流量持续增长，数据库系统是否能够轻松扩展。
```

2020-03-08 03:14 UTC, ngaut commented on session3/chapter2/key-vis.md
> +业务开发人员面对这些问题有时候一脸问号，脑子里面快速过了一遍自己的业务，我大概有 一百多张表，每个都有增删改查/CRUD，还有各种统计汇总的业务，有很多请求还是用户触发的，这些问题真的是很难回答。很多业务的访问模式都可以在 TiDB dashboard 里面比较直观的观测到， DBA 和开发者能够一眼发现系统的读写比例，哪里有热点，甚至能够精确到哪个数据块，哪些索引，也能预测如果流量持续增长，数
addressed

2020-03-08 03:43 UTC, baurine commented on session3/chapter2/key-vis.md
> +- 在热图中向上或向下滚动。
```suggestion
- 在热图中向上或向下滚动
```

2020-03-08 03:44 UTC, baurine commented on session3/chapter2/key-vis.md
> +如果我们把光标移动到金黄色的热点上还能看到更具体的提示，如下图所示，可以看到每分钟的流量为 165.25 兆/每秒, 访问的表名是 sbtest1， 访问的对象是表的一个索引，索引的名字是 k_1, 我们也能看到这个块在存储层对应的 key 范围，即图中展示的 start key 和 end key。
> 可以看到每分钟的流量为 165.25 兆/每秒,

这句话让人 confuse，到底是每分钟还是每秒，图片中是 165.25M bytes/min

2020-03-08 03:46 UTC, breezewish approved these changes

2020-03-08 04:11 UTC, merged