tiflash-in-action
pingcap-incubator/tidb-in-action pull request #79
Opened 2020-03-07 01:31 UTC by honor100

TiFlash 的使用

2020-03-07 03:45 UTC, solotzg commented
format please follow：https://github.com/pingcap-incubator/tidb-in-action/blob/master/session1/chapter1/tidb-architecture.md

2020-03-07 03:45 UTC, solotzg commented on session1/chapter9/tiflash-in-action.md
> +##TiSpark 读取 TiFlash
please check before commit

2020-03-07 04:14 UTC, solotzg commented on session1/chapter9/tiflash-in-action.md
> +同样的，对于指定 hint 的表，如果没有 tiflash 副本，查询会报该表不存在该 tiflash 副本的 错。
`副本的 错` remove useless space

2020-03-07 06:03 UTC, solotzg commented on session1/chapter9/tiflash-in-action.md
> +用户可以使用TiDB或者TiSpark读取TiFlash，TiDB适合用于中等规模的OLAP计算，而
所有中英文之间需要用空格隔开

2020-03-07 06:19 UTC, honor100 commented on session1/chapter9/tiflash-in-action.md
> +用户可以使用TiDB或者TiSpark读取TiFlash，TiDB适合用于中等规模的OLAP计算，而
"remove useless space"，刚才让去掉的！？

2020-03-07 13:09 UTC, ilovesoup requested changes

2020-03-07 13:09 UTC, ilovesoup commented on session1/chapter9/tiflash-in-action.md
> +ALTER TABLE ​table_name​ SET TIFLASH REPLICA ​count​ [LOCATION LABELS location_labels​]
暂时可以不提 location label，因为这个功能未必会在 4.0 一起放开，暂时没有太大场景需求。

2020-03-07 13:09 UTC, ilovesoup commented on session1/chapter9/tiflash-in-action.md
> +1. 在 spark-defaults.conf 文件中添加 spark.tispark.use.tiflash=true
可能把conf放到markdown代码段比较好？

2020-03-07 13:09 UTC, ilovesoup commented on session1/chapter9/tiflash-in-action.md
> +4. Thriftserver 通过 beeline 连接后实时设置: setspark.tispark.use.tiflash=true;
是不是吃掉一个空格？set后面

2020-03-07 13:47 UTC, solotzg commented on session1/chapter9/tiflash-in-action.md
> +# 使用
大标题需要用文章的中文标题

2020-03-08 05:04 UTC, honor100 commented on session1/chapter9/tiflash-in-action.md
> +ALTER TABLE ​table_name​ SET TIFLASH REPLICA ​count​ [LOCATION LABELS location_labels​]
好的

2020-03-08 05:35 UTC, solotzg approved these changes
LGTM

2020-03-08 06:09 UTC, winkyao approved these changes

2020-03-08 06:10 UTC, merged