Update 6.1.3 高并发的唯一序列号生成方案
pingcap-incubator/tidb-in-action pull request #811
Opened 2020-04-05 15:43 UTC by stillicel

### What problem does this PR solve? 
This PR is try to fix #748 
### How to contact you? 
- WeChat: stillicel

2020-04-06 02:19 UTC, AndreMouche requested changes
感谢修改，唯一的建议是可以改得更狠一点，代码尽量少出现在技术文档里哦

2020-04-06 02:19 UTC, AndreMouche commented on session4/chapter6/serial-number.md
> +* worker node id：默认 22 位。
与 15 行重了

2020-04-06 02:19 UTC, AndreMouche commented on session4/chapter6/serial-number.md
> +当大流量写入时，由于 worker node id 位于生成 ID 的中部并且没有重复，不同节点生成的 ID 之间就不会并排在一起，因此写入就会被打散到各个 region。
这边我没有理解，如果是 `{$sign}{$delta-seconds}{$worker-node-id}` 来生成，在 `worker node id` 之前的 `delta-seconds` 已经是连续的了，我的理解该规则生成的 Key 也就是连续的了，如果直接往 TiDB 写入，还是会有热点问题？ 不知道是不是有误解呢？

2020-04-06 02:19 UTC, AndreMouche commented on session4/chapter6/serial-number.md
> +  `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
表结构的定义，我觉得用表格展示比贴 SQL 语句可读性要更强一些

2020-04-06 02:19 UTC, AndreMouche commented on session4/chapter6/serial-number.md
> +		    // getMaxNoFromBusiTable方法：从数据表中通过max方法获取最大号段值
其实上面已经说过实现逻辑了，具体代码实现建议作为本节小作业让读者自己去思考。这个代码可以作为小作业的参考答案之一。

2020-04-06 03:06 UTC, stillicel commented on session4/chapter6/serial-number.md
> +		    // getMaxNoFromBusiTable方法：从数据表中通过max方法获取最大号段值
有道理. 我稍后来看一下在去掉全部代码之后, 能否仍然把实现思路讲清楚.

2020-04-06 03:07 UTC, stillicel commented on session4/chapter6/serial-number.md
> +  `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
同意. 我稍后改用表格形式展示table定义, 因为不能假定所有读者都熟悉MySQL语法.

2020-04-06 03:08 UTC, stillicel commented on session4/chapter6/serial-number.md
> +* worker node id：默认 22 位。
这一段原作直接copy自那个开源项目的文档, 我会再修饰一下语言, 避免出现歧义.

2020-04-06 03:14 UTC, stillicel commented on session4/chapter6/serial-number.md
> +当大流量写入时，由于 worker node id 位于生成 ID 的中部并且没有重复，不同节点生成的 ID 之间就不会并排在一起，因此写入就会被打散到各个 region。
在worker-node-id之后还有13位 sequence id.  这样,  ID的前面29位和后面35位是两段不相关的单调递增值. 因此, 只要生成的速率足够高, 则生成的ID整体上趋向于随机分布的.

2020-04-06 18:57 UTC, stillicel commented on session4/chapter6/serial-number.md
> +当大流量写入时，由于 worker node id 位于生成 ID 的中部并且没有重复，不同节点生成的 ID 之间就不会并排在一起，因此写入就会被打散到各个 region。
你说得对。 snowflake产生的ID直接作为TiDB主键仍然会带来热点问题。 可以进行bit-reverse将其打散开来。

2020-04-06 19:03 UTC, stillicel commented on session4/chapter6/serial-number.md
> +* worker node id：默认 22 位。
去掉了重复行； 调整了delta seconds 和 worker node id的说明文字。

2020-04-06 19:05 UTC, stillicel commented on session4/chapter6/serial-number.md
> +  `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
改成了表格形式， 并参考美团公开的一份文档简化了表结构以便于理解。

2020-04-06 19:05 UTC, stillicel commented on session4/chapter6/serial-number.md
> +		    // getMaxNoFromBusiTable方法：从数据表中通过max方法获取最大号段值
去掉了全部代码， 感觉上整个号段分配翻案的思路还是能说清楚的。

2020-04-07 06:55 UTC, AndreMouche approved these changes
LGTM

2020-04-07 06:56 UTC, merged