Session3 chapter4 read write metrics
pingcap-incubator/tidb-in-action pull request #829
Opened 2020-04-08 05:43 UTC by sandy20140407

### What problem does this PR solve? 
This PR is trying to fix #717 
### How to contact you? 
- Email:
- Telephone:
- WeChat:
- Others: @sandy20140407

2020-04-08 14:01 UTC, AndreMouche commented on session3/chapter4/read-write-metrics.md
>  1. 从 Memtable 从查找，如果没有找到，则从 SST 文件中查找
```suggestion
1. 从 Memtable 中查找，如果没有找到，则从 SST 文件中查找
```

2020-04-08 14:01 UTC, AndreMouche commented on session3/chapter4/read-write-metrics.md
>  2. 二分查找包含这个 key 的文件（每一个文件包含一个 key 的范围，如果目标 key 没有在这个范围之中，则跳过这个文件，另 L0 的文件是可能重叠的，需要查 L0 的所有文件）
```suggestion
2. 除了 L0 外，对于每一层二分查找包含这个 key 的文件（每一个文件包含一个 key 的范围，如果目标 key 没有在这个范围之中，则跳过这个文件，另 L0 的文件是可能重叠的，需要查 L0 的所有文件）
```

2020-04-08 14:01 UTC, AndreMouche commented on session3/chapter4/read-write-metrics.md
>  3. 检查 Bloom filter，这个文件是否包含这个 key（前一步骤中是判断 key 是否可能位于这个文件是根据文件的范围，比如 A 文件的范围是 [1, 10)，这个时候如果 key 是 11，那么直接跳过这个文件，如果 key 是 5，则这个文件可能包含这个返回；本步骤通过 bloom filter 判断是否包含这个 key，能通过前一步骤说明这个 key 位于这个范围，这一步检查是
```suggestion
3. 对于每个 sst 文件，会先刷到 block-cache 中。然后检查 Bloom filter，这个文件是否包含这个 key（前一步骤中是判断 key 是否可能位于这个文件是根据文件的范围，比如 A 文件的范围是 [1, 10)，这个时候如果 key 是 11，那么直接跳过这个文件，如果 key 是 5，则这个文件可能包含这个返回；本步骤通过 bloom filter 判断是否包含这个 key，能通过前一步骤说明这个 key 位于这个范围，这一步检查是否这个文件包含这个 key，比如 A 的范围是 [1, 10)，里面的 key 有 (1,3,5,7,9)，这个时候 6 虽然落在范围 [1, 10)，但是并没有包含在这个文件）
```

2020-04-08 14:01 UTC, AndreMouche commented on session3/chapter4/read-write-metrics.md
>  3. 检查 Bloom filter，这个文件是否包含这个 key（前一步骤中是判断 key 是否可能位于这个文件是根据文件的范围，比如 A 文件的范围是 [1, 10)，这个时候如果 key 是 11，那么直接跳过这个文件，如果 key 是 5，则这个文件可能包含这个返回；本步骤通过 bloom filter 判断是否包含这个 key，能通过前一步骤说明这个 key 位于这个范围，这一步检查是
我觉得这个例子在这里举得很不好，可以结合整个过程来举例
另外 bloom filter 说不存在就是真的不存在，但是 bloom filter 说存在可能数据并不存在。既然要讲这个过程，就需要讲清楚。

2020-04-08 14:33 UTC, sandy20140407 commented on session3/chapter4/read-write-metrics.md
>  3. 检查 Bloom filter，这个文件是否包含这个 key（前一步骤中是判断 key 是否可能位于这个文件是根据文件的范围，比如 A 文件的范围是 [1, 10)，这个时候如果 key 是 11，那么直接跳过这个文件，如果 key 是 5，则这个文件可能包含这个返回；本步骤通过 bloom filter 判断是否包含这个 key，能通过前一步骤说明这个 key 位于这个范围，这一步检查是
视频课程里有个例子挺好的，当时听懂了，现在忘记了。
只记得结论，bloom filter 说不存在就是真的不存在，但是 bloom filter 说存在可能数据并不存在。

2020-04-12 05:31 UTC, AndreMouche commented on session3/chapter4/read-write-metrics.md
> +3. 对于每个 sst 文件，会先刷到 block-cache 中。然后检查 Bloom filter，这个文件是否包含这个 key（前一步骤中是判断 key 是否可能位于这个文件是根据文件的范围，比如 A 文件的范围是 [1, 10)，这个时候如果 key 是 11，那么直接跳过这个文件，如果 key 是 5，则这个文件可能包含这个返回；本步骤通过 bloom filter 判断是否包含这个
```suggestion
3. 检查 Bloom filter，这个文件是否可能包含这个 key：
	- 如果 Bloom filter 判断为否，则该 key 一定不在本 block 中。
	- 如果判断为是，则该 key 可能在本 block 中。
```
这一块逻辑问题比较大。首先是先
通过 Index Block 二分定位到 key 所在的 Blcok,
 然后才是在这个 block 中 检查 Bloom filter，这个文件是否可能包含这个 key：

2020-04-12 05:34 UTC, AndreMouche requested changes
Rocksdb 的读流程原文写得逻辑存在问题，需要调整，参考文档 https://github.com/facebook/rocksdb/wiki/Rocksdb-BlockBasedTable-Format

2020-04-12 10:14 UTC, kissmydb commented on session3/chapter4/read-write-metrics.md
> +3. 对于每个 sst 文件，会先刷到 block-cache 中。然后检查 Bloom filter，这个文件是否包含这个 key（前一步骤中是判断 key 是否可能位于这个文件是根据文件的范围，比如 A 文件的范围是 [1, 10)，这个时候如果 key 是 11，那么直接跳过这个文件，如果 key 是 5，则这个文件可能包含这个返回；本步骤通过 bloom filter 判断是否包含这个
```suggestion
3.  SST 文件中的查询
     - 通过 SST 的 Index Block 二分定位到 Key 所在的 Block
     - 在这个 Block 中进行 Bloom filter 检查，确定这个文件是否可能包含这个 Key：
       - 如果 Bloom filter 判断为 false，则该 key 一定不在本 block 中。
       - 如果 Bloom filter 判断为 ture，则该 key 可能在本 block 中。
```

2020-04-12 10:26 UTC, kissmydb commented on session3/chapter4/read-write-metrics.md
> +3. 对于每个 sst 文件，会先刷到 block-cache 中。然后检查 Bloom filter，这个文件是否包含这个 key（前一步骤中是判断 key 是否可能位于这个文件是根据文件的范围，比如 A 文件的范围是 [1, 10)，这个时候如果 key 是 11，那么直接跳过这个文件，如果 key 是 5，则这个文件可能包含这个返回；本步骤通过 bloom filter 判断是否包含这个
我在下面改了一下，看看对否

2020-04-12 10:47 UTC, kissmydb approved these changes
LGTM

2020-04-12 10:48 UTC, merged