Update 第三部分 3.5 SQL 慢查询内存表
pingcap-incubator/tidb-in-action pull request #852
Opened 2020-04-11 18:27 UTC by stillicel

### What problem does this PR solve? 
#712 
### How to contact you? 
- WeChat: stillicel

2020-04-12 05:42 UTC, AndreMouche requested changes
把字段解释去掉的依旧是？其他地方有重复么？

2020-04-12 06:26 UTC, stillicel commented
Slow Query 日志的字段说明在官方文档里有解释，不必原样 copy 到书里。日志格式可能随版本变化微调，是比较容易过期的部分。

2020-04-12 06:27 UTC, stillicel commented
> 把字段解释去掉的依旧是？其他地方有重复么？
Slow Query 日志的字段说明在官方文档里有解释，不必原样 copy 到书里。日志格式可能随版本变化微调，是比较容易过期的部分。

2020-04-12 11:05 UTC, kissmydb commented
跟官网重复没有关系，本书的目的也是跳出官网，给新接触的人的入手 handbook。建议解释可以恢复回来~~

2020-04-12 14:28 UTC, stillicel commented
@kissmydb 
- 恢复了慢查询日志格式和字段的说明。
- 调整了一些段落结构，使行文前后连贯。

2020-04-13 01:06 UTC, AndreMouche approved these changes

2020-04-13 01:07 UTC, merged